[package]
name = "wascap"
version = "0.7.0"
authors = ["wasmCloud Team"]
edition = "2018"
description = "Wascap - WebAssembly Standard Capabilities. Library for extracting, embedding, and validating claims"
license = "Apache-2.0"
homepage = "https://wasmcloud.com"
documentation = "https://docs.rs/wascap"
readme = "README.md"
keywords = ["jwt", "crypto", "ed25519", "security", "webassembly"]
categories = ["cryptography", "authentication", "wasm"]

[dependencies]
log = "0.4.14"
env_logger = "0.8.2"
serde_derive = "1.0.123"
serde = "1.0.123"
nkeys = "0.1.0"
base64 = "0.13.0"
serde_json = "1.0.61"
nuid = "0.3.0"
parity-wasm = "0.42.1"
lazy_static = "1.4.0"
ring = "0.16.20"
data-encoding = "2.3.2"
chrono-humanize = "0.2.1"
chrono = "0.4.19"