[package]
name = "wascap"
version = "0.10.0"
authors = ["wasmCloud Team"]
edition = "2018"
description = "Wascap - wasmCloud Capabilities. Library for extracting, embedding, and validating claims"
license = "Apache-2.0"
homepage = "https://wasmcloud.com"
documentation = "https://docs.rs/wascap"
readme = "README.md"
keywords = ["jwt", "crypto", "ed25519", "security", "webassembly"]
categories = ["cryptography", "authentication", "wasm"]

[dependencies]
log = "0.4.14"
env_logger = "0.10.0"
serde_derive = "1.0.123"
serde = "1.0.123"
nkeys = "0.2.0"
base64 = "0.13.0"
serde_json = "1.0.61"
nuid = "0.4.1"
#wasmparser = { git = "https://github.com/bytecodealliance/wasm-tools"}
wasmparser = "0.102.0"
wasm-gen = "0.1.4"
wasm-encoder = "0.25.0"
lazy_static = "1.4.0"
ring = "0.16.20"
data-encoding = "2.3.2"
humantime = "2.1"